version: "3.8"

services:
  ab:
   build:
     context: .
   ports:
    - "8000:8000"
   volumes:
    - ./src:/src
   environment:
    - SECRET_KEY=${SECRET_KEY}
    
    - EMAIL_ADDRESS=${EMAIL_ADDRESS}
    - EMAIL_PASSWORD=${EMAIL_PASSWORD}

    - DB_NAME=askb_db
    - DB_HOST=db
    - DB_USER=${DB_USERNAME}
    - DB_PASSWORD=${DB_PASSWORD}

   command: >
    sh -c "python3 manage.py call_db &&
           python3 manage.py migrate &&
           python3 manage.py runserver 0.0.0.0:8000"
   
   depends_on:
    - db

   tty: true
  db:
    image: postgres:10-alpine

    environment:
     - POSTGRES_DB=askb_db
     - POSTGRES_USER=${DB_USERNAME}
     - POSTGRES_PASSWORD=${DB_PASSWORD}