---

name: checks
on: [push]
jobs:
  test:
   name: unit tests
   runs-on: ubuntu-20.04
   steps:
     - name: Login with actions
       uses: docker/login-action@v1
       with:
        username: ${{secrets.DOCKERHUB_USER}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
     
     - name: check out
       uses: actions/checkout@v2

     - name: Set up project secrets 
       env: 
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
       run: echo "SECRET_KEY=${SECRET_KEY}" >> $GITHUB_ENV
         
     - name: Test
       run: docker compose run --rm ab sh -c "python3 manage.py test"
    
