---

name: checks
on: [push]
jobs:
  test:
   name: unit tests
   runs-on: ubuntu-20.04
   steps:
     - name: Login with actions
       uses: docker/login-action@v1
       with:
        username: ${{secrets.GITHUB_USER}}
        password: ${{secrets.GITHUB_TOKEN}}
     
     - name: check out
       uses: actions/checkout@v2

     - name: Test
       run: docker compose run --rm ab sh -c "python3 manage.py test"
    
